
# Site settings
url: http://screwdriver.cd
title: screwdriver.cd
analytics: UA-88158708-2

social:
  - title: slack
    url: http://slack.screwdriver.cd
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/screwdriver-cd
  - title: github
    url: http://github.com/screwdriver-cd
  - title: tumblr
    url: http://blog.screwdriver.cd

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - screwdriver.yaml
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - Rakefile
  - ci
  - deploy.sh


# Team names, titles and social links
people:

- name: Alan Dong
  pic: adong
  position: adong
  github: https://github.com/adong

- name: Dao Lam
  pic: d2lam
  position: D2
  github: https://github.com/d2lam

- name: Dekus Lam
  pic: DekusDenial
  position: Over 9000
  github: https://github.com/DekusDenial

- name: Jithin Emmanuel
  pic: jithine
  position: RESTafarian
  github: https://github.com/jithine

- name: Kevin Lu
  pic: klu909
  position: as himself
  github: https://github.com/klu909

- name: Lakshminarasimhan Parthasarathy
  pic: parthasl
  position: hmm
  github: https://github.com/parthasl

- name: Pritam Paul
  pic: pritamstyz4ever
  position: likes hikes
  github: https://github.com/pritamstyz4ever

- name: Tiffany Kyi
  pic: tkyi
  position: Turtle Addict
  github: https://github.com/tkyi

- name: Keisuke Kumada
  pic: kumada626
  position: kumada626
  github: https://github.com/kumada626

- name: Shota Yoshika
  pic: s-yoshika
  position: Yo
  github: https://github.com/s-yoshika

- name: Teppei Minegishi
  pic: sakka2
  position: sakka2
  github: https://github.com/sakka2

- name: Hiroki Takatsuka
  pic: tk3fftk
  position: tk3fftk
  github: https://github.com/tk3fftk

- name: Kenta Kawaharada
  pic: wahapo
  position: wa
  github: https://github.com/wahapo

- name: Yuya Takahashi
  pic: y-takaha5hi
  position: "16 shots per second"
  github: https://github.com/y-takaha5hi

- name: Yoshiyuki Watanabe
  pic: yoshwata
  position: yoshwata
  github: https://github.com/yoshwata

- name: Yuichi Sawada
  pic: yuichi10
  position: Slam-dunker
  github: https://github.com/yuichi10

- name: Kazuki Kokufuda
  pic: kkokufud
  position: kkokufud
  github: https://github.com/kkokufud

- name: Ibuki Miyagami
  pic: ibu1224
  position: ibu1224
  github: https://github.com/ibu1224

- name: Kazuyuki Kai
  pic: kkisic
  position: kkisic
  github: https://github.com/kkisic

- name: Naoaki Sato
  pic: sugarnaoming
  position: sugarnaoming
  github: https://github.com/sugarnaoming

- name: Mitsuru Takigahira
  pic: MysticDoll
  position: MysticDoll
  github: https://github.com/MysticDoll
